### ISSUE TITLE
Is the order on the readme the intended reading?

### ISSUE THREAD

**Issue by danielms215** [pauli-space/foundations_for_deep_learning#1]
#question

Thank you for putting this together! Is the order on the readme the suggested reading order? Or is it just a collection of papers, to be read in any way?

Thanks

**Comment by AidanRocke** [comment]
That's a good question. I personally think that we can reach similar conclusions whether we study a deep model purely using applied mathematics, neuroscience or information theory. Eventually, I think that all of these perspectives will develop into complementary theories in the same way that we have mathematically equivalent theories of quantum mechanics but for that to happen it might be very useful to have toy models(not just toy datasets like MNIST). 

For this reason, I think that people should start with the papers that they're comfortable with and branch out from there. :)

**Comment by 2Hossion** [comment]
Please give me API support

**Comment by AidanRocke** [comment]
@danielms215 I would add that [J. Schmidhuber's historical overview of deep learning](https://arxiv.org/abs/1404.7828) is excellent. I would actually say that this overview was a great starting point for myself

If you prefer videos [R. Salakhutdinov's deep learning tutorials](https://www.youtube.com/watch?v=-SY4-GkDM8g) are amazing in my opinion.

**Comment by AidanRocke** [comment]
@2Hossion If you would like to collaborate on this project, it would be easier to discuss the details of a collaboration via email. You can reach me via aidanrocke@gmail.com
