### ISSUE TITLE
The pdf not showing up

### ISSUE THREAD

**Issue by SevenOf-Nine** [pauli-space/foundations_for_deep_learning#4]
Please check the file: https://github.com/pauli-space/foundations_for_deep_learning/blob/master/classics/deep_learning_in_neural_networks.pdf

It is neither opening in the browser nor can I download. (Windows 10, Mozilla)

**Comment by mdibaiee** [comment]
I had the same issue, tried with different PDF readers with no success, then I found the paper here, and it seems to work fine: http://people.idsia.ch/~juergen/DeepLearning2July2014.pdf

**Comment by AidanRocke** [comment]
@SevenOf-Nine @mdibaiee Thanks for pointing this out. I just fixed this. :)

**Comment by amitmanchanda1995** [comment]
Hey @AidanRocke it is still not working.

**Comment by AidanRocke** [comment]
Ok. It should work now. :)
